fixup! Rebase: [facebook][compiler-rt] Rebase ASAN fiber support (T10286520) onto toolchain/server/upstream
Summary:
MSVC rejected this code. You shouldn't reinterpret_cast to the same type.

fixes:

```
P:\open\server-llvm\compiler-rt\lib\asan\asan_thread.h(101): error C2440: 'reinterpret_cast': cannot convert from '__sanitizer::uptr' to '__sanitizer::uptr'
P:\open\server-llvm\compiler-rt\lib\asan\asan_thread.h(101): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
```

Test Plan: build compiler-rt and asked @akrieger to build it on windows.

Reviewers: wlei, peix, #compiler_toolchain

Reviewed By: wlei

Subscribers: akrieger

Differential Revision: https://phabricator.intern.facebook.com/D71506340