[server-llvm-19][ICP] Fix warnings
Summary:
This backports https://github.com/llvm/llvm-project/commit/2bdc0da4d7a26ab023ee03b877fb4a3e4beb070c
Follow-up to D83268471

This patch fixes:

  llvm/lib/Transforms/Instrumentation/IndirectCallPromotion.cpp:845:12:
  error: variable 'RemainingVTableCount' set but not used
  [-Werror,-Wunused-but-set-variable]

  llvm/lib/Transforms/Instrumentation/IndirectCallPromotion.cpp:306:23:
  error: private field 'PSI' is not used
  [-Werror,-Wunused-private-field]

Here are a couple of domino effects:

- Once I remove PSI, I need to update the contructor and its caller.

- Once I remove RemainingVTableCount, I don't need TotalCount, so I am
  updating the caller as well.

Test Plan: sandcastle

Rollback Plan:

Reviewers: gpastukhov, #compiler_toolchain, wenlei

Reviewed By: gpastukhov

Differential Revision: https://phabricator.intern.facebook.com/D85892330