[server-llvm-19] Fix build errors with a `LLVM_ENABLE_MODULES=ON` build (#107654)
Summary:
Backport of https://github.com/llvm/llvm-project/commit/9a84afefa1ab98c5315ad2e7a78e8cdc6372e153

The errors fixed were:
* llvm-project/llvm/include/llvm/Analysis/SyntheticCountsUtils.h:33:22:
error: missing '#include <__fwd/vector.h>'; default argument of 'vector'
must be defined before it is used
*
llvm-project/clang/include/clang/Tooling/Inclusions/StandardLibrary.h:41:15:
error: missing '#include <vector>'; 'vector' must be declared before it
is used
*
llvm-project/llvm/include/llvm/Transforms/InstCombine/InstCombiner.h:83:3:
error: missing '#include "llvm/ADT/PostOrderIterator.h"';
'ReversePostOrderTraversal' must be declared before it is used

Test Plan:
```
llvm-fb-cli build -s staging-mcypark-pgo-modules-19 -d scratch/server-llvm/staging-mcypark-pgo-modules-19 --build-mode FULL --llvm-fb-version 19
```
https://www.internalfb.com/sandcastle/workflow/3728980491470291181

Reviewers: wangwei, #compiler_toolchain, ayermolo, ych, matthiasb

Reviewed By: wangwei

Differential Revision: https://phabricator.intern.facebook.com/D74614617

Tags: oncall, accept2ship, llvm-server-oncall