Rebase: Recommit D14256619 - nullability for smart pointers (T15268145)
Summary:
This was dropped with green light from the original author on D31098489. But turns out the change is still needed, because many staging builds have failed without it, e.g. https://www.internalfb.com/intern/sandcastle/job/9007199744277641
```
admarket/rex/AppShardedDelegates.cpp:173:26: error: nullability specifier '_Nullable' cannot be applied to non-pointer type 'std::shared_ptr<Network>'
std::shared_ptr<Network> FOLLY_NULLABLE AppShardedDelegates::getGlobalNetwork(
                         ^
```

Manual rebase conflict history:
https://phabricator.intern.facebook.com/D31212073

Test Plan: ninja check-clang

Reviewers: #compiler_toolchain

Subscribers: yfeldblum, dominik, phabricatorlinter

Differential Revision: https://phabricator.intern.facebook.com/D55660329

Tasks: T15268145

Tags: server-llvm