[llvm-dwp] Turn debug info overflow into warning
Summary:
After my upstream change, with backport, https://reviews.llvm.org/D130395 we error out when overflow of .debug_info section is detected in llvm-dwp utility.

This caused quite a few services to stop building.
https://fb.workplace.com/groups/fbcode/permalink/5344896165547179/

In this diff I added a downstream option to still print out an error, but finish creating DWP file.
@christylee will add fbcode option to trigger this: D38328628.

Test Plan:
hg update --noninteractive --traceback -r 'f12f258ce18a917128a48e08b1c6f02888aa674d' -C

buck build @mode/opt-split-dwarf -c fbcode.dwp=true //search/dufusion:du_fusion_server-dwp

```
[ayermolo@devbig765.prn2 ~/fbsource2/fbcode/buck-out/opt/gen/search/dufusion/du_fusion_server-dwp__srcs] ~/local/llvm-build-release/bin/llvm-dwp -e buck-out/opt/gen/search/dufusion/du_fusion_server -o buck-out/opt/last/du_fusion_server.dwp
error: debug information section offset is greater than 4GB
[ayermolo@devbig765.prn2 ~/fbsource2/fbcode/buck-out/opt/gen/search/dufusion/du_fusion_server-dwp__srcs] ls -lat buck-out/opt/last/du_fusion_server.dwp
ls: cannot access 'buck-out/opt/last/du_fusion_server.dwp': No such file or directory
```

```
[ayermolo@devbig765.prn2 ~/fbsource2/fbcode/buck-out/opt/gen/search/dufusion/du_fusion_server-dwp__srcs] ~/local/llvm-build-release/bin/llvm-dwp -e buck-out/opt/gen/search/dufusion/du_fusion_server -o buck-out/opt/last/du_fusion_server.dwp -continue-on-cu-index-overflow
Warning: Your debug sections grew to more than 4GB. Although DWP file has been created, it is corrupt. This can affect other tools like llvm-profgen
[ayermolo@devbig765.prn2 ~/fbsource2/fbcode/buck-out/opt/gen/search/dufusion/du_fusion_server-dwp__srcs] ls -lat buck-out/opt/last/du_fusion_server.dwp
-rw-r--r-- 1 ayermolo users 11088386904 Aug  1 16:09 buck-out/opt/last/du_fusion_server.dwp
```

Reviewers: wenlei, matthiasb

Reviewed By: wenlei, matthiasb

Subscribers: christylee

Differential Revision: https://phabricator.intern.facebook.com/D38331903

Tasks: T127866823

Tags: oncall, oncallteam-compilers