[ELF][Distributed ThinLTO] Allow thinlink to generate full input list for final link
Summary:
It is the internal version of https://reviews.llvm.org/D130975 to unblock buck2 distributed ThinLTO rollout. There is still on-going discussion on how to properly support both bitcode and native object file indexing in distributed ThinLTO thinlink. See https://reviews.llvm.org/D130229 and https://reviews.llvm.org/D130975 for more context. Once a final upstream resolution is reached, we'll revert this diff and its llvm-fb backports.


## Summary
Add new option `--thinlto-full-index` to work together with `--thinlto-index-only=` to produce an extended index list including both native and bitcode objects.

### NOTE
The list also includes regular archives (.a) to the point where any of its members is first extracted. Even though we have converted archives to thin archives, there are still a few left at this moment,
```
fbcode/third-party-buck/platform010/build/IntelComposerXE/mkl/lib/intel64/libmkl_intel_lp64.a
fbcode/third-party-buck/platform010/build/IntelComposerXE/mkl/lib/intel64/libmkl_core.a
fbcode/third-party-buck/platform010/build/IntelComposerXE/mkl/lib/intel64/libmkl_intel_thread.a
fbcode/third-party-buck/platform010/build/glibc/lib/libc_nonshared.a
```
Since lld can't access an unextracted archive member, its archive name is included in the index. This is the latest point that the archive needs to be in the input.

`--as-needed/--no-as-needed` and `--start-group/--end-group` are omitted in the extended index list.

### More context:
For file name `thinlto.index` given to `--thinlto-index-only=`, the new option writes the extended list to `thinlto.index.full`. Then distributed backend can use `thinlto.index` to guide its compilation and `thinlto.index.full` can be fed into final link as the full input list with the intended resolution order.

lld scans object files and resolves its symbols in input order:
* For non-lazy object file (binary, shared object, bitcode object and regular object), it extracts, parses and resolves its symbols as it is encountered.
* For lazy object file (bitcode object and regular object), it does not actively extract and resolve its symbols, instead It only creates a `LazyObjectKind` symbol in the symbol table. When a symbol defined in the lazy object file is referenced, the file is extracted, parsed and resolved just like a non-lazy object file.

Currently `--thinlto-index-only` appends to the list for non-lazy bitcode object file as they are encountered and lazy bitcode object files when they are extracted. It basically emits the symbol resolution order for those files. However when user inputs consist of both prebuilt native objects and bitcode objects, the list is incomplete and it is hard to achieve the same symbol resolution order during final link to produce the same result as the inputs were going through local ThinLTO.

`--thinlto-full-index` appends to the list for on-lazy object files as they are encountered, and lazy object files when they are extracted. And if such object is from a regular archive, the archive name is inserted into the list when any of its member is first extracted. This list can be fed into final link as the full input list with the intended resolution order. 

Since the above list also includes linker added object and system libraries, the final link should use `-nostdlib` to not include them twice.
 
During local thinlto, the symbol table can also be updated after a bitcode object is compiled and its output (`lto.tmp`) is parsed as regular object file. This simulates the behavior of such object file is added to the end of user inputs. However, this shouldn't affect the resolution order, because the symbols from this object file have already taken place in symbol table, and new symbols created during function importing and promotion shouldn't conflict with others in different modules. 

### Example:
```
> echo 'int g() { return 0; }' > a.cpp
> echo 'int g() { return 1; } void f() { return; }' > b.cpp
> echo 'void f(); int g(); int main() { [[clang::always_inline]] f(); [[clang::noinline]] return g(); }' > c.cpp

# compile
> clang++ -c -flto=thin -O2 c.cpp -o c.o
> clang++ -c -flto=thin -O2 b.cpp -o b.o
> clang++ -c -O2 a.cpp -o a.o
```

#### local thinlto
```
> clang++ -flto=thin -fuse-ld=lld -Wl,--start-lib a.o -Wl,--end-lib -Wl,--start-lib b.o -Wl,--end-lib -Wl,--start-lib c.o -Wl,--end-lib -o local
> ./local
> echo $?
1
```
* `g` is defined in both `a.o` and `b.o`. All object files are lazy by user input. 
* `g` is first seen in `a.o`, because it goes before `b.o` in input order. But since it is a lazy object, no extraction happens. A `LazyObjectKind` symbol is created for `g` in the symbol table.
* First extraction happens when `main` (defined is `c.o`) is seen. `c.o` is now non-lazy, and going through the resolution process as regular bitcode object.
* The chain reaction causes `b.o` to be extracted, because `f` is not defined in `c.o`. `b.o` is now non-lazy, and going through the resolution process as regular bitcode object.
* `g` is replaced by the one defined in `b.o` with `DefinedKind`.

#### dist_thinlto with `--thinlto-index-only`
```
> clang++ -flto=thin -fuse-ld=lld -Wl,--thinlto-index-only=thinlto.index,--thinlto-emit-imports-files -Wl,--start-lib a.o -Wl,--end-lib -Wl,--start-lib b.o -Wl,--end-lib -Wl,--start-lib c.o -Wl,--end-lib

> cat thinlto.index
c.o
b.o

> clang++ -O2 -c -x ir b.o -fthinlto-index=b.o.thinlto.bc -o b.native.o
> clang++ -O2 -c -x ir c.o -fthinlto-index=c.o.thinlto.bc -o c.native.o
> clang++ -fuse-ld=lld -Wl,--start-lib a.o -Wl,--end-lib c.native.o b.native.o -o dist1
ld.lld: error: duplicate symbol: g()
>>> defined at a.cpp
>>>            a.o:(g())
>>> defined at b.cpp
>>>            b.native.o:(.text+0x0)
```
* thinlink performs the same symbol resolution steps as local thinlto, but it only records the order for bitcode objects. The order follows the extraction order.
* Without knowing the global order, `a.o` is put back in final link even through it was never extracted during thinlink symbol resolution.
* Because `f` is inlined, when `c.native.o` is parsed, it sees the undefined `g` is defined in `a.o`, which causes an extraction of `a.o`, and replaces the entry with `DefinedKind` in symbol table.
* When `b.native.o` is processed, it finds a previous definition already exists.

#### dist_thinlto with `--thinlto-full-index`
```
> clang++ -flto=thin -fuse-ld=lld -Wl,--thinlto-index-only=thinlto.index,--thinlto-full-index,--thinlto-emit-imports-files,--thinlto-prefix-replace=';opt/' -Wl,--start-lib a.o -Wl,--end-lib -Wl,--start-lib b.o -Wl,--end-lib -Wl,--start-lib c.o -Wl,--end-lib

> cat thinlto.index
opt/c.o
opt/b.o

> cat thinlto.index.full
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/Scrt1.o
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crti.o
/usr/lib/gcc/x86_64-redhat-linux/8/crtbeginS.o
opt/c.o
opt/b.o
/usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.so
/lib64/libm.so.6
/lib64/libmvec.so.1
/lib64/libgcc_s.so.1
/lib64/libc.so.6
elf-init.oS
/lib64/ld-linux-x86-64.so.2
/lib64/libgcc_s.so.1
/usr/lib/gcc/x86_64-redhat-linux/8/crtendS.o
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crtn.o

> clang++ -O2 -c -x ir b.o -fthinlto-index=opt/b.o.thinlto.bc -o opt/b.o
> clang++ -O2 -c -x ir c.o -fthinlto-index=opt/c.o.thinlto.bc -o opt/c.o
> clang++ -fuse-ld=lld -nostdlib @thinlto.index.full -o dist2
> ./dist2
> echo $?
1
```
* The output `thinlto.index` has all bitcode object needed for compilation.
* The output `thinlto.index.full` includes all the needed object files for final link. If a lazy object is not extracted, it is not on the list, such as `a.o`. The final link will only see one definition from `b.o`. 

Test Plan: ninja check-lld

Reviewers: ayermolo, fnz, wenlei, christylee, hoy, #compiler_toolchain

Reviewed By: ayermolo, fnz, wenlei, hoy

Subscribers: ayermolo, wenlei, hoy, zhuhan

Differential Revision: https://phabricator.intern.facebook.com/D38157138

Tasks: T124883009