Recommit D14256619 - nullability for smart pointers (T15268145)
Summary:
This was dropped with green light from the original author on D31098489. But turns out the change is still needed, because many staging builds have failed without it, e.g. https://www.internalfb.com/intern/sandcastle/job/9007199744277641
```
admarket/rex/AppShardedDelegates.cpp:173:26: error: nullability specifier '_Nullable' cannot be applied to non-pointer type 'std::shared_ptr<Network>'
std::shared_ptr<Network> FOLLY_NULLABLE AppShardedDelegates::getGlobalNetwork(
                         ^
```

Test Plan: ninja check-clang

Reviewers: wenlei, wangwei, #compiler_toolchain

Reviewed By: wenlei

Subscribers: yfeldblum, dominik, phabricatorlinter

Differential Revision: https://phabricator.intern.facebook.com/D31212073

Tasks: T15268145

Tags: server-llvm

Signature: 31212073:1632781616:bc3934626eef03c50553c9d2e0fa12c0c939793c